title:
  label: Titre du site
  description: Intitulé du site par défaut

description:
  label: Description du site
  description: Fournit une courte description du contenu d'une page web. Elle est souvent affichée dans les résultats de recherche sous le titre de la page.

logo:
  label: Logo du projet
  description: Logo de l'enseigne

image:
  label: Image de pre-visualisation
  description: Image de pre-visualisation du site par défaut

favicon:
  label: Favicon
  description: Petite icône représentant un site web qui est affichée dans l'onglet du navigateur, les signets et les résultats de recherche.

table:
  buttons:
    edit: Modifier
  columns:
    label: Nom du paramètre
    value: Valeur du paramètre

breadcrumb:
  label: Paramètres du site

policies:
  global:
    view:
      label: Voir les paramètres du site
      description: Pouvoir voir les paramètres du site
    edit:
      label: Modifier les paramètres du site
      description: Pouvoir modifier les paramètres du site

notifications:
  update: Les paramètres du site ont été mis à jour avec succès.
  invalidate: Le cache du site a été invalidé.
